CREATE TABLE USERS
(
    EMAIL         VARCHAR2(255)                                 NOT NULL,
    PASSWORD_HASH VARCHAR2(255)                                 NOT NULL,
    NICKNAME      VARCHAR2(255)                                 NOT NULL,
    CREATED_AT    TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    PRIMARY KEY (EMAIL)
);

CREATE TABLE EMAIL_VERIFICATIONS
(
    CODE       VARCHAR2(255)                                                        NOT NULL,
    EMAIL      VARCHAR2(255)                                                        NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP                        NOT NULL,
    EXPIRE_AT  TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP + INTERVAL '30' MINUTE NOT NULL,
    PRIMARY KEY (CODE)
);

CREATE TABLE CATEGORIES
(
    ID      NUMBER GENERATED AS IDENTITY,
    NAME    VARCHAR2(20) NOT NULL,
    "ORDER" NUMBER,
    PRIMARY KEY (ID)
);

CREATE TABLE POSTS
(
    ID               NUMBER GENERATED AS IDENTITY,
    TYPE             NUMBER                                        NOT NULL,
    DONE             NUMBER(1)                DEFAULT 0            NOT NULL,
    TITLE            VARCHAR2(255),
    AUTHOR_EMAIL     VARCHAR2(255)                                 NOT NULL,
    ITEM_CATEGORY_ID NUMBER,
    ITEM_NAME        VARCHAR2(255),
    ITEM_DATE        TIMESTAMP WITH TIME ZONE,
    ITEM_LOCATION    VARCHAR2(255),
    CONTENT          VARCHAR2(1000)                                NOT NULL,
    CREATED_AT       TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT       TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    PRIMARY KEY (ID)
);

CREATE OR REPLACE TRIGGER POSTS_SET_UPDATED_AT
    BEFORE UPDATE
    ON POSTS
    FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;

CREATE TABLE COMMENTS
(
    ID           NUMBER GENERATED AS IDENTITY,
    POST_ID      NUMBER                                        NOT NULL,
    AUTHOR_EMAIL VARCHAR2(255)                                 NOT NULL,
    CONTENT      VARCHAR2(1000)                                NOT NULL,
    PARENT_ID    NUMBER,
    CREATED_AT   TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT   TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    DELETED_AT   TIMESTAMP WITH TIME ZONE,
    PRIMARY KEY (ID)
);

CREATE OR REPLACE TRIGGER COMMENTS_SET_UPDATED_AT
    BEFORE UPDATE
    ON COMMENTS
    FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;

CREATE TABLE ATTACHMENTS
(
    ID         VARCHAR2(50),
    POST_ID    NUMBER                                        NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    PRIMARY KEY (ID)
);
